name: PHPUnit Tests

on: [push, pull_request]

jobs:
  pehaape-junid:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

  # web-deploy:
  #   name: 🎉 Deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: 🚚 Get latest code
  #     uses: actions/checkout@v4
    
  #   - name: 📂 Sync files
  #     uses: SamKirkland/FTP-Deploy-Action@v4.3.5
  #     with:
  #       server: ssh.helbolund.dk
  #       username: helbolund.dk
  #       password: ${{ secrets.SFTP_PASSWORD }}

  sftp-peploy:
    name: Upload build to hosting environment
    runs-on: ubuntu-latest
    steps:
    - name: Morten Helbo Lund
      uses: Atyn/Simple-SFTP@0.0.2
      with:
        url: sftp://helbolund.dk:${{ secrets.SFTP_PASSWORD }}@ssh.helbolund.dk/customers/5/e/0/helbolund.dk/httpd.www/php_test
        local-directory: path/to/artifact
