name: Deploy to one.com

on: [push, pull_request]

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LFTP
      run: sudo apt-get install lftp

    - name: Deploy files via SFTP
      env:
        SFTP_HOST: ssh.helbolund.dk
        SFTP_USERNAME: helbolund.dk
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_PORT: 22
      run: |
        lftp -d -u helbolund.dk,$SFTP_PASSWORD -e "set sftp:auto-confirm yes; mirror -R /home/runner/work/php_test/php_test/src/ /customers/5/e/0/helbolund.dk/httpd.www/php_test/; quit" -p 22 sftp://ssh.helbolund.dk

  php-junit:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt
