name: Deploy to one.com

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LFTP
      run: sudo apt-get install lftp

    - name: Deploy files via SFTP
      env:
        SFTP_HOST: ssh.helbolund.dk
        SFTP_USERNAME: helbolund.dk
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
        SFTP_PORT: 22
      run: |
        lftp -d -u helbolund_dk,$SFTP_PASSWORD -e "mirror -R /home/runner/work/php_test/php_test/src/ /customers/5/e/0/helbolund.dk/httpd.www/php_test/; quit" -p 22 ssh.helbolund.dk
        
      # lftp -u $SFTP_USERNAME,$SFTP_PASSWORD -e "mirror -R /home/runner/work/php_test/php_test/src /customers/5/e/0/helbolund.dk/httpd.www/php_test; quit" -p $SFTP_PORT $SFTP_HOST

  pehaape-junid:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p path/to/artifact
    - run: echo hello > path/to/artifact/world.txt
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: path/to/artifact/world.txt

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    - run: pwd
    - run: ls -al /home/runner/work/php_test/php_test
    - run: cat /home/runner/work/php_test/php_test/src/Person.php
    # - name: 📂 Sync files
    #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
    #   with:
    #     server: ssh.helbolund.dk
    #     username: helbolund.dk
    #     password: $(( secrets.SFTP_PASSWORD ))

    - name: 
      # uses: actions/checkout@v4
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: ssh.helbolund.dk
        username: helbolund.dk
        password: ${{ secrets.SFTP_PASSWORD }}
        port: 22
        uploads: |
          /home/runner/work/php_test/php_test/src/Person.php => /customers/5/e/0/helbolund.dk/httpd.www/php_test/.
        ignore: |
          !index.html
          !.htaccess

  # upload:
  #   name: Upload build to hosting environment
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: MHL_step
  #     uses: Atyn/Simple-SFTP
  #     with:
  #       url: sftp://USERNAME:PASSWORD@example.com/remote-directory
  #       local-directory: build-output
          
  # sftp-peploy:
  #   name: Upload build to hosting environment
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Morten Helbo Lund
  #     uses: Atyn/Simple-SFTP@latest
  #     with:
  #       url: sftp://helbolund.dk:${{ secrets.SFTP_PASSWORD }}@ssh.helbolund.dk/customers/5/e/0/helbolund.dk/httpd.www/php_test
  #       local-directory: path/to/artifact
